import type { Metadata } from "next";
import { newsreader, poppins } from "@/lib/font";
import "../globals.css";
import Navbar from "@/components/organism/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Login | Jong Coffee",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative antialiased`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
        <Toaster richColors />
      </body>
    </html>
  );
}
